= Building Apps around the Event Mesh
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

Understanding how to structure an application can be challenging. Different
architectural patterns often lack insight into how to build day-to-day solutions
that are often at least as complex as the business they operate in. 

This solution pattern is written to make it obvious and to show simple, yet
elegant, correct, and comprehensive way of building software, either in
greenfield or even in legacy projects. This solution leverages the
https://www.redhat.com/en/technologies/cloud-computing/openshift/serverless[Red Hat Serverless]
Eventing component, which implements the https://www.redhat.com/en/topics/integration/what-is-an-event-mesh[Event Mesh] pattern.

*Contributors:* https://github.com/cardil[Chris Suszynski]

++++
 <br>
++++
[NOTE]
====
Solution Patterns help you understand the art of the possible with Red Hat's 
portfolio, and not intended to be used as is for production environments. You
are welcome to use any part of this solution pattern for your own workloads.
====
[#use-cases]
== Use cases

Event mesh pattern simplifies the operational complexity of distributed 
applications, making architectures more resilient and scalable.

Common use cases that can be addressed with this architecture include:

- *Correctness* and *consistency* across distributed applications and services, 
  without the hassles of _Event Sourcing_.
- *Modernising* legacy applications by extracting smaller *microservices* into a 
  distributed and eventually consistent system.
- *Enabling communication* with external services, that can be easily tested
  using a common *developer toolkit*.

include::01-pattern.adoc[]
